# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'WalinnsAPI-Swift'

  # Pods for StarterProject

  target 'StarterProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarterProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
