# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterProject-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    pod 'WalinnsAPI'
    
 
  # Pods for StarterProject-ObjC

  target 'StarterProject-ObjCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarterProject-ObjCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
